Fix GSettings when XDG_DATA_DIRS is overridden
GSettings requires that glib-2.0 be found in XDG_DATA_DIRS or the
program crashes.  To avoid making an already long line much longer, move
the list of symlinks that need to be made to a separate file.

Tested by (1) creating the symlink manually in a qube and finding that
the problem went away and (2) checking that `make install` worked
properly.

diff --git a/misc/Makefile b/misc/Makefile
--- a/misc/Makefile
+++ b/misc/Makefile
@@ -27,9 +27,14 @@ install:
 	    marker-vm \
 	    qubes-master-key.asc
 	install -D -m 0644 mime-globs $(DESTDIR)$(QUBESDATADIR)/mime-override/globs
-	for i in X11 aclocal appdata augeas backgrounds bash-completion desktop-directories dict doc empty games gnome help icons idl info licenses locale man metainfo mime-info misc omf pixmaps sounds themes wayland-sessions xsessions; do \
-		ln -sf "../../$$i" $(DESTDIR)$(QUBESMIMEDIR)/"$$i"; \
-	done
+	IFS=; while read -r i; do \
+		case $$i in \
+			(''|'#'*) continue;; \
+			(*[!A-Za-z0-9._-]*) \
+				printf 'ERROR: bad data directory "%s"\n' "$$i" >&2; exit 1;;\
+		esac; \
+		ln -sf "../../$$i" $(DESTDIR)$(QUBESMIMEDIR); \
+	done < data-dirs
 	$(RM) mime/icons
 	umask 022 && cp -r applications mime '$(DESTDIR)$(QUBESMIMEDIR)'
 	install -m 0755 -d $(DESTDIR)$(BINDIR)
