Handle zramctl command failure gracefully
Elide unnecessary failure when no zram devices are setup.

(cherry picked from commit e044f0727a9f957227d5745817aa98ac3df2e5a9)

diff --git a/vm-systemd/setup-minimal-vm b/vm-systemd/setup-minimal-vm
--- a/vm-systemd/setup-minimal-vm
+++ b/vm-systemd/setup-minimal-vm
@@ -38,7 +38,7 @@ disable_zram() {
     ln -nsf /dev/null /run/systemd/zram-generator.conf
     systemctl daemon-reload
     if command -v zramctl >/dev/null; then
-        zramctl -r zram0
+        zramctl -r zram0 || true # Elide unnecessary failure when no zram devices are setup.
     fi
 }
 
