qvm-copy: add message about file/directory not found before qrexec
(cherry picked from commit 9b69805f979622e42d9bff324352a5bceeaa71e2)

diff --git a/qubes-rpc/qvm-copy b/qubes-rpc/qvm-copy
--- a/qubes-rpc/qvm-copy
+++ b/qubes-rpc/qvm-copy
@@ -73,6 +73,13 @@ if [ "$PROGRESS_TYPE" = console ] ; then
     export FILECOPY_TOTAL_SIZE
 fi
 
+for path in "$@"; do
+    if [ ! -e "$path" ]; then
+        echo "File or directory not found: $path"
+        exit 1
+    fi
+done
+
 /usr/lib/qubes/qrexec-client-vm -- "$VM" qubes.Filecopy /usr/lib/qubes/qfile-agent "$@"
 
 if [ "$OPERATION_TYPE" = "move" ] ; then
