init: run resize2fs on /rw before mounting
In case of private.img was resized while the VM was powered off.

diff --git a/vm-init.d/qubes-core b/vm-init.d/qubes-core
--- a/vm-init.d/qubes-core
+++ b/vm-init.d/qubes-core
@@ -55,6 +55,7 @@ start()
 	mkdir -p /var/run/qubes
 
 	if [ -e /dev/xvdb ] ; then
+		resize2fs /dev/xvdb 2> /dev/null || echo "'resize2fs /dev/xvdb' failed"
 		mount /rw
 
         if ! [ -d /rw/home ] ; then
