Fix resizing of /rw partition (private.img)
Offline resize requires to run fsck -f first. Because we support only
growing that image, we can simply use online resize instead.

This finally fixes qubesos/qubes-issues#772

diff --git a/vm-init.d/qubes-core b/vm-init.d/qubes-core
--- a/vm-init.d/qubes-core
+++ b/vm-init.d/qubes-core
@@ -60,8 +60,8 @@ start()
 			mkfs.ext4 -m 0 -q /dev/xvdb || exit 1
 		fi
 
-		resize2fs /dev/xvdb 2> /dev/null || echo "'resize2fs /dev/xvdb' failed"
 		mount /rw
+		resize2fs /dev/xvdb 2> /dev/null || echo "'resize2fs /dev/xvdb' failed"
 
         if ! [ -d /rw/home ] ; then
             echo
