Fix resizing of /rw partition (private.img)
Offline resize requires to run fsck -f first. Because we support only
growing that image, we can simply use online resize instead.

This finally fixes qubesos/qubes-issues#772

(cherry picked from commit 65bc22fd1d1be613d45ed1b8cb635b419c662969)

Conflicts:
	vm-init.d/qubes-core
	vm-systemd/mount-home.sh

diff --git a/vm-init.d/qubes-core b/vm-init.d/qubes-core
--- a/vm-init.d/qubes-core
+++ b/vm-init.d/qubes-core
@@ -55,8 +55,8 @@ start()
 	mkdir -p /var/run/qubes
 
 	if [ -e /dev/xvdb ] ; then
-		resize2fs /dev/xvdb 2> /dev/null || echo "'resize2fs /dev/xvdb' failed"
 		mount /rw
+		resize2fs /dev/xvdb 2> /dev/null || echo "'resize2fs /dev/xvdb' failed"
 
         if ! [ -d /rw/home ] ; then
             echo
