Enable SELinux support
This sets up the needed file context substitutions.  It also provides
polices for qfile-unpacker and the dom0-provided kernel module
directory.

diff --git a/rpm_spec/core-agent.spec.in b/rpm_spec/core-agent.spec.in
--- a/rpm_spec/core-agent.spec.in
+++ b/rpm_spec/core-agent.spec.in
@@ -29,6 +29,7 @@
 %else
 %define with_sysvinit 1
 %endif
+%bcond_without selinux
 
 %if 0%{?rhel} == 8
 %define plateform_python3_sitelib %(/usr/libexec/platform-python -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib())')
@@ -292,6 +293,50 @@ Requires: Thunar
 %description thunar
 Thunar support for Qubes VM tools
 
+%if %{with selinux}
+%package selinux
+Summary: SELinux policy for Qubes VMs
+License: GPLv2+
+
+# The following is based on %%selinux_requires, which has the following license:
+# Copyright (C) 2017 Red Hat, Inc. All rights reserved.
+#
+#   Author: Petr Lautrbach <plautrba@redhat.com>
+#   Author: Lukáš Vrabec <lvrabec@redhat.com>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+%if 0%fedora
+Requires: selinux-policy >= %fedora
+Requires(post): selinux-policy-base >= %fedora
+%else
+Requires: selinux-policy
+Requires(post): selinux-policy-base
+%endif
+Requires(post): libselinux-utils
+BuildRequires: selinux-policy
+BuildRequires: selinux-policy-devel
+
+%description selinux
+SELinux policy for the Qubes VM tools.  This allows the Qubes VM tools to run in
+a VM with SELinux enforcing, as is the default on Red Hat-family distributions.
+
+%files selinux
+%_datadir/selinux/packages/targeted/qubes-qfile-unpacker.pp
+
+%endif
+
 %define kde_service_dir /usr/share/kde4/services
 %define kde5_service_dir /usr/share/kservices5/ServiceMenus
 
@@ -300,7 +345,7 @@ Thunar support for Qubes VM tools
 
 %build
 %{?set_build_flags}
-make BACKEND_VMM=@BACKEND_VMM@
+make BACKEND_VMM=@BACKEND_VMM@ WITH_SELINUX=%with_selinux
 make -C doc manpages
 
 %pre
@@ -329,7 +374,7 @@ usermod -L root
 
 %install
 
-make install-vm PYTHON=%{__python3} DESTDIR=$RPM_BUILD_ROOT SYSTEM_DROPIN_DIR=%{_unitdir} SYSLIBDIR=/usr/lib
+make install-vm PYTHON=%{__python3} DESTDIR=$RPM_BUILD_ROOT SYSTEM_DROPIN_DIR=%{_unitdir} SYSLIBDIR=/usr/lib WITH_SELINUX=%with_selinux
 make -C app-menu DESTDIR=$RPM_BUILD_ROOT install
 make -C boot/redhat DESTDIR=$RPM_BUILD_ROOT install
 make -C config-overrides DESTDIR=$RPM_BUILD_ROOT install
@@ -497,6 +542,7 @@ if [ ! -e /etc/xdg/autostart/notification-daemon.desktop ]; then
 fi
 exit 0
 
+%if %{without selinux}
 %triggerin -- selinux-policy
 
 . /usr/lib/qubes/init/functions
@@ -508,6 +554,7 @@ if ! is_protected_file /etc/selinux/config; then
     setenforce 0 2>/dev/null
 fi
 exit 0
+%endif
 
 %post network-manager
 
@@ -563,6 +610,48 @@ fi
 %systemd_preun qubes-iptables.service
 %systemd_preun qubes-network.service
 %systemd_preun qubes-updates-proxy.service
+
+%if %{with selinux}
+%post selinux
+
+%selinux_modules_install %{_datadir}/selinux/packages/targeted/qubes-qfile-unpacker.pp
+
+contexts='### QUBES START ###\
+/rw/home /home\
+/rw/config/NM-system-connections /etc/NetworkManager/system-connections\
+/rw/bind-dirs /\
+/usr/local/etc /etc\
+/usr/local/share /usr/share\
+/usr/local/libexec /usr/libexec\
+/usr/local/games /usr/games\
+/usr/local/bin /usr/bin\
+/usr/local/lib /usr/lib\
+/usr/local/src /usr/src\
+/usr/local/include /usr/include\
+/usr/local/sbin /usr/sbin\
+### QUBES END ###'
+flock --no-fork -- %_selinux_store_policy_path/semanage.read.LOCK \
+sed -Ei -- "/^### QUBES START ###\$/,/^### QUBES END ###\$/{
+\$c\
+$contexts
+d
+}
+\$a\
+$contexts
+" /etc/selinux/targeted/contexts/files/file_contexts.subs
+
+%preun selinux
+if [ "$1" -eq 0 ] && ! grep -E '^SELINUX=(disabled|permissive)$' /etc/selinux/config; then
+  echo 'qubes-core-agent-selinux cannot be uninstalled with SELinux in enforcing mode' >&2
+  exit 1
+fi
+flock --no-fork -- %_selinux_store_policy_path/semanage.read.LOCK \
+sed -Ei -- "/^### QUBES START ###\$/,/^### QUBES END ###\$/d" \
+  /etc/selinux/targeted/contexts/files/file_contexts.subs
+%selinux_modules_uninstall %{_datadir}/selinux/packages/targeted/qubes-qfile-unpacker.pp %{_datadir}/selinux/packages/targeted/qubes-xendriverdomain.pp
+exit 0
+
+%endif
 
 %postun thunar
 if [ "$1" = 0 ]; then
